---

- hosts: localhost
  # become: yes
  roles:
    - role: ../../ansible-role-vault
      vars:
        vault_auth_methods:
          - jwt
        vault_secret_engines:
          - ssh
        vault_policies:
          - name: gitlab
            hcl: |
              path "gitlab/secret*" {
                capabilities = [ "read" ]
              }

...