---

- hosts: localhost
  become: yes
  roles:
    - role: ../../ansible-role-vault
      vars:
        vault_docker_expose_api: 127.0.0.1:9200:{{ vault_docker_api_port }}
        # vault_storage_config: |
        #   storage "file" {
        #       path    = "/vault/file"
        #   }
        vault_auth_methods:
          - jwt
        vault_secret_engines:
          - engine: ssh
          - engine: kv
            options:
              version: 1
        vault_policies:
          - name: gitlab
            hcl: |
              path "gitlab/secret*" {
                capabilities = [ "read" ]
              }
        vault_writes:
          - path: auth/jwt/config
            force: yes
            kv:
              jwks_url: https://gitlab.with42.de/-/jwks
              bound_issuer: gitlab.with42.de
          - path: auth/jwt/empty
            force: yes

...