---

- name: Ensure prepare dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Ensure vault config
  ansible.builtin.include_tasks: vault_config.yml

- name: Ensure vault
  community.docker.docker_container:
    name:    vault
    image:   vault:{{ vault_version }}
    command: server
    capabilities:
      - ipc_lock
    ports:
      - "{{ vault_docker_expose_api }}"
      - "{{ vault_docker_expose_cluster }}"
    env:
      VAULT_ADDR: http://127.0.0.1:{{ vault_docker_api_port }}
    volumes:
      - "{{ vault_home }}/logs:/vault/logs"
      - "{{ vault_home }}/file:/vault/file"
      - "{{ vault_home }}/config:/vault/config"
    restart_policy:             always
    container_default_behavior: compatibility
    # state: "{{ vault_docker_container_state }}"

- name: Ensure vault init
  ansible.builtin.include_tasks: vault_init.yml
  run_once: true

- name: Ensure vault is active
  ansible.builtin.include_tasks: vault_wait.yml
  run_once: true

- name: Ensure vault root token
  ansible.builtin.include_tasks: vault_root_token.yml
  when: vault_create_root_token
  run_once: true

- name: Ensure vault enable auth methods
  ansible.builtin.include_tasks: vault_auth_enable.yml
  loop: "{{ vault_auth_methods }}"
  loop_control:
    loop_var: _vault_auth_method
  run_once: true

- name: Ensure vault enable secret engines
  ansible.builtin.include_tasks: vault_secrets_enable.yml
  loop: "{{ vault_secret_engines }}"
  loop_control:
    loop_var: _vault_secret_engine
  run_once: true

- name: Ensure vault policy writes
  ansible.builtin.include_tasks: vault_policy_write.yml
  loop: "{{ vault_policy_writes }}"
  loop_control:
    loop_var: _vault_policy_write
    label: "{{ _vault_policy_write.name }}"
  run_once: true

- name: Ensure vault writes
  ansible.builtin.include_tasks: vault_write.yml
  loop: "{{ vault_writes }}"
  loop_control:
    loop_var: _vault_write
    label: "{{ _vault_write.path }}"
  run_once: true

- name: Ensure vault kv deletes
  ansible.builtin.include_tasks: vault_kv_delete.yml
  loop: "{{ vault_kv_deletes }}"
  loop_control:
    loop_var: _vault_kv_delete
    label: "{{ _vault_kv_delete.path }}"
  run_once: true

- name: Ensure vault kv puts
  ansible.builtin.include_tasks: vault_kv_put.yml
  loop: "{{ vault_kv_puts }}"
  loop_control:
    loop_var: _vault_kv_put
    label: "{{ _vault_kv_put.path }}"
  run_once: true

- name: Ensure vault app role credentials
  ansible.builtin.include_tasks: vault_approle.yml
  loop: "{{ vault_approles }}"
  loop_control:
    loop_var: _vault_approle
  run_once: true

...
