---

- name: Ensure prepare community.docker.docker_container
  ansible.builtin.include_tasks: docker_container.yml

- name: Ensure vault config
  ansible.builtin.include_tasks: vault_config.yml

- name: Ensure vault
  community.docker.docker_container:
    name:    vault
    image:   vault:{{ vault_version }}
    command: server
    capabilities:
      - ipc_lock
    ports:
      - 0.0.0.0:8200:8200
      - 0.0.0.0:8201:8201
    volumes:
      - "{{ vault_home }}/logs:/vault/logs"
      - "{{ vault_home }}/file:/vault/file"
      - "{{ vault_home }}/config:/vault/config"
    restart_policy:             always
    container_default_behavior: compatibility
    # state: "{{ vault_docker_container_state }}"

- name: Ensure vault init
  ansible.builtin.include_tasks: vault_init.yml

- name: Wait vault active
  ansible.builtin.shell:
    cmd: docker exec vault vault status -format=json -address=http://127.0.0.1:8200 
  register: _vault_status_output
  until: _vault_status_output.stdout.find("leader_") != -1
  retries: 10
  delay: 2
  changed_when: false

- name: Ensure vault enable auth jwt
  ansible.builtin.shell:
    cmd: docker exec -e VAULT_TOKEN='{{ _vault_root_token }}' vault vault auth enable -address=http://127.0.0.1:8200 jwt | tee {{ vault_auth_jwt_file }}
    creates: "{{ vault_auth_jwt_file }}"

...