---

- name: Ensure Hashicorp key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Ensure Hashicorp repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main
    update_cache: yes
    state: present

- name: Ensure vault package installed
  ansible.builtin.apt:
    name: vault={{ vault_version }}

- name: Ensure hold vault package version
  dpkg_selections:
    name: vault
    selection: hold

- name: Ensure _vault_command_prefix
  ansible.builtin.set_fact:
    _vault_command_prefix: "VAULT_ADDR=http://127.0.0.1:{{ vault_api_port }} vault"

- name: Ensure _vault_command_postfix
  ansible.builtin.set_fact:
    _vault_command_postfix: ''

...
