---

- name: Ensure vault file/raft path
  ansible.builtin.file:
    path:  "{{ vault_home_path }}/file/raft"
    state: directory
    mode:  g-rwx

- name: Ensure vault config
  ansible.builtin.template:
    src:  main.hcl.j2
    dest: "{{ vault_home_path }}/config/main.hcl"
    mode: g-rwx

...
