---

- name: Ensure unzip
  ansible.builtin.apt:
    name: unzip

- name: Ensure linux user vault
  ansible.builtin.user: 
    name: vault

- name: Ensure vault binary
  ansible.builtin.unarchive:
    remote_src: true
    src:        "{{ vault_binary_archive_src }}"
    dest:       /usr/local/bin
    mode:       ugo+rx,go-w
    creates:    /usr/local/bin/vault

- name: Ensure vault server systemd service configuration exists
  ansible.builtin.template:
    src: templates/vault.service.j2
    dest: /etc/systemd/system/vault.service
    mode: go-w

- name: reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure _vault_command_prefix
  ansible.builtin.set_fact:
    _vault_command_prefix: "VAULT_ADDR={{ vault_internal_api_addr }} {% if vault_tls_client_ca_file is defined and vault_tls_client_ca_file %}VAULT_CACERT={{ vault_tls_client_ca_file }}{% endif %} vault"

- name: Ensure _vault_command_postfix
  ansible.builtin.set_fact:
    _vault_command_postfix: ''

- name: Ensure _vault_command_interactive
  ansible.builtin.set_fact:
    _vault_command_interactive: ''

...
