---

- name: Ensure vault home
  ansible.builtin.file:
    path:  "{{ vault_home_path }}"
    state: directory
    mode:  o-rwx,g-rwx

- name: Ensure vault config path
  ansible.builtin.file:
    path:  "{{ vault_config_path }}"
    state: directory
    mode:  o-rwx,g-rwx

- name: Ensure vault policies path
  ansible.builtin.file:
    path:  "{{ vault_config_path }}/policies"
    state: directory
    mode:  o-rwx,g-rwx

- name: Ensure vault tmp path
  ansible.builtin.file:
    path:  "{{ vault_config_path }}/tmp"
    state: directory
    mode:  o-rwx,g-rwx

- name: Ensure vault logs path
  ansible.builtin.file:
    path:  "{{ vault_home_path }}/logs"
    state: directory
    mode:  o-rwx,g-rwx

- name: Ensure vault file/raft path
  ansible.builtin.file:
    path:  "{{ vault_home_path }}/file/raft"
    state: directory
    mode:  o-rwx,g-rwx

- name: Ensure vault config
  ansible.builtin.template:
    src:  main.hcl.j2
    dest: "{{ vault_home_path }}/config/main.hcl"
    mode:  o-rwx,g-rwx

...
