---

- name: Ensure vault docker
  community.docker.docker_container:
    name:    vault
    image:   vault:{{ vault_version }}
    command: server
    capabilities:
      - ipc_lock
    network_mode: host
    ports:
      - "{{ vault_docker_expose_api }}"
      - "{{ vault_docker_expose_cluster }}"
    env:
      VAULT_ADDR: http://127.0.0.1:{{ vault_docker_api_port }}
    volumes:
      - "{{ vault_home_path }}/logs:/vault/logs"
      - "{{ vault_home_path }}/file:/vault/file"
      - "{{ vault_home_path }}/config:/vault/config"
    restart_policy:             always
    container_default_behavior: compatibility
    # state: "{{ vault_docker_container_state }}"

...
