---

- name: Ensure vault file/raft path
  ansible.builtin.file:
    path:  "{{ vault_home_path }}/file/raft"
    state: directory
    group: vault
    owner: vault
    mode:  o-rwx
  # notify: restart vault service

- name: Ensure vault config
  ansible.builtin.template:
    src:  vault.hcl.j2
    dest: "{{ vault_config_path }}/vault.hcl"
    mode: o-rwx
  # notify: restart vault service
    
- name: Ensure vault policies path
  ansible.builtin.file:
    path:  "{{ vault_config_path }}/policies"
    state: directory
    group: vault
    owner: vault
    mode:  o-rwx
  # notify: restart vault service
    
...
