---

- name: Ensure _vault_secret_engine_options
  ansible.builtin.set_fact:
    _vault_secret_engine_options: "{{ _vault_secret_engine.options | default({}) | default(omit) }}"
  run_once: true

- name: Ensure initialize _vault_secret_engine_options_string
  ansible.builtin.set_fact:
    _vault_secret_engine_options_string: ''
  run_once: true

- name: Ensure _vault_secret_engine_options_string
  ansible.builtin.set_fact:
    _vault_secret_engine_options_string: "{{ _vault_secret_engine_options_string | default('') }} -{{ item.key }}={{ item.value }}"
  loop: "{{ query('dict', _vault_secret_engine_options) }}"
  loop_control:
    label: "{{ item.key }}"
  run_once: true

# - name: Print _vault_secret_engine_options_string
#   ansible.builtin.debug:
#     msg: "_vault_secret_engine_options_string: {{ _vault_secret_engine_options_string }}"
#   run_once: yes

- name: Ensure _vault_secret_engine_path
  ansible.builtin.set_fact:
    _vault_secret_engine_path: "{{ _vault_secret_engine_options.path | default(_vault_secret_engine.engine) | default(omit) }}"

# - name: Print _vault_secret_engine_path
#   ansible.builtin.debug:
#     msg: "_vault_secret_engine_path: {{ _vault_secret_engine_path }}"
#   run_once: yes

- name: Ensure vault enable secret engine
  ansible.builtin.shell:
    cmd: >
      {{ _vault_command_prefix }} -e VAULT_TOKEN='{{ _vault_root_token }}' {{ _vault_command_postfix }} secrets enable {{ _vault_secret_engine_options_string }} {{ _vault_secret_engine.engine }}
      && touch {{ vault_home_path }}/ansible_done_vault_secret_enable_{{ _vault_secret_engine.engine }}_{{ _vault_secret_engine_path }}
    creates: "{{ vault_home_path }}/ansible_done_vault_secret_enable_{{ _vault_secret_engine.engine }}_{{ _vault_secret_engine_path }}"
  run_once: true

...
