---

- name: Read vault init file stat on host
  ansible.builtin.stat:
    path: "{{ vault_home_path }}/ansible_done_vault_init"
  ignore_errors: true
  register: _vault_init_file_stat_host

- name: Set fact _vault_initialized_host
  ansible.builtin.set_fact:
    _vault_initialized_host: "{{ _vault_init_file_stat_host.stat.exists }}"

- name: Read vault init file stat on localhost
  ansible.builtin.stat:
    path: ansible_done_vault_init_localhost
  ignore_errors: true  
  delegate_to: localhost
  register: _vault_init_file_stat_localhost

- name: Set fact _vault_initialized_localhost
  ansible.builtin.set_fact:
    _vault_initialized_localhost: "{{ _vault_init_file_stat_localhost.stat.exists }}"

- name: Ensure vault init when not initialized before
  ansible.builtin.shell:
    cmd: >
      {{ _vault_command_prefix }} {{ _vault_command_postfix }} operator init -key-shares {{ vault_key_shares }} -key-threshold {{ vault_key_threshold }} -format=json >{{ vault_home_path }}/.ansible_done_vault_init &&
      openssl enc -aes-256-cbc -pbkdf2 -pass env:SECRET -in {{ vault_home_path }}/.ansible_done_vault_init -out {{ vault_home_path }}/ansible_done_vault_init &&
      rm {{ vault_home_path }}/.ansible_done_vault_init
    creates: "{{ vault_home_path }}/ansible_done_vault_init"
  environment:
    SECRET: "{{ vault_encrypt_secret }}"
  when: not _vault_initialized_host and not _vault_initialized_localhost

- name: Slurp encrypted vault init info
  ansible.builtin.slurp:
    src: "{{ vault_home_path }}/ansible_done_vault_init"
  register: _vault_init_file_slurp

- name: Ensure vault init file on localhost
  ansible.builtin.copy:
    dest:    _vault_init_file_stat_localhost
    content: "{{ _vault_init_file_slurp['content'] | b64decode }}"
    mode:    "u+rw,g-wx,o-rwx"
  delegate_to: localhost
  when: not _vault_initialized_localhost

- name: Ensure vault init file on host
  ansible.builtin.copy:
    dest: "{{ vault_home_path }}/ansible_done_vault_init"
    src:  _vault_init_file_stat_localhost
    mode: "u+rw,g-wx,o-rwx"
  when: not _vault_initialized_host

- name: Ensure decrypt ansible_done_vault_init
  ansible.builtin.shell:
    cmd: >
      openssl enc -aes-256-cbc -pbkdf2 -pass env:SECRET -d -out {{ vault_home_path }}/.ansible_done_vault_init -in {{ vault_home_path }}/ansible_done_vault_init
  environment:
    SECRET: "{{ vault_encrypt_secret }}"
  changed_when: false

- name: Slurp vault init info
  ansible.builtin.slurp:
    src: "{{ vault_home_path }}/.ansible_done_vault_init"
  register: _vault_init_file_slurp

- name: Ensure remove "{{ vault_home_path }}/.ansible_done_vault_init"
  ansible.builtin.file:
    path: "{{ vault_home_path }}/.ansible_done_vault_init"
    state: absent
  changed_when: false

- name: Set fact _vault_init_info from slurp
  ansible.builtin.set_fact:
    _vault_init_info: "{{ _vault_init_file_slurp['content'] | b64decode }}"

- name: Set fact _vault_unseal_keys
  ansible.builtin.set_fact:
    _vault_unseal_keys:  "{{ _vault_init_info.unseal_keys_b64 }}"

- name: Set fact _vault_root_token
  ansible.builtin.set_fact:
    _vault_root_token: "{{ _vault_init_info.root_token }}"
  when: not vault_revoke_root_token or not _vault_initialized

- name: Print fact _vault_unseal_keys
  ansible.builtin.debug:
    msg: "_vault_unseal_keys: {{ _vault_unseal_keys }}"
  when: vault_show_unseal_keys

- name: Print fact _vault_root_token
  ansible.builtin.debug:
    msg: "_vault_root_token: {{ _vault_root_token }}"
  when: vault_show_initial_root_token

- name: Set facts vault status exit codes  ## noqa var-naming
  ansible.builtin.set_fact:
    _VAULT_STATUS_UNSEALED: 0
    _VAULT_STATUS_ERROR:    1
    _VAULT_STATUS_SEALED:   2

- name: Get vault status output
  ansible.builtin.shell:
    cmd: >
      {{ _vault_command_prefix }} {{ _vault_command_postfix }} status -format=json
  register: _vault_status_output
  failed_when: _vault_status_output.rc == _VAULT_STATUS_ERROR
  changed_when: false

- name: Ensure unseal vault
  ansible.builtin.shell:
    cmd: >
      {{ _vault_command_prefix }} {{ _vault_command_postfix }} operator unseal {{ _vault_unseal_keys[_vault_unseal_key_index] }}
  loop: "{{ range(0, vault_key_threshold) | list }}"
  loop_control:
    index_var: _vault_unseal_key_index
  when: _vault_status_output.rc == _VAULT_STATUS_SEALED

...
