---

- name: Ensure Hashicorp key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: lsb_release -cs
  ansible.builtin.command:
    cmd: lsb_release -cs
  register: _vault_lsb_release_cs_results
  changed_when: false

- name: Set fact _vault_lsb_release_cs
  ansible.builtin.set_fact:
    _vault_lsb_release_cs: "{{ _vault_lsb_release_cs_results.stdout }}"

- name: Ensure Hashicorp repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ _vault_lsb_release_cs }} main
    update_cache: yes
    state: present

- name: Ensure vault package installed
  ansible.builtin.apt:
    name: "vault{% if vault_version != 'latest' %}={{ vault_version }}{% endif %}"

- name: Ensure hold vault package version
  dpkg_selections:
    name: vault
    selection: hold

- name: Ensure _vault_command_prefix
  ansible.builtin.set_fact:
    _vault_command_prefix: "VAULT_ADDR=http://127.0.0.1:{{ vault_api_port }} vault"

- name: Ensure _vault_command_postfix
  ansible.builtin.set_fact:
    _vault_command_postfix: ''

...
