---

- name: Ensure _vault_secret_engine_options
  ansible.builtin.set_fact:
    _vault_secret_engine_options: "{{ _vault_secret_engine.options | default({}) | default(omit) }}"
  run_once: yes

- name: Ensure initialize _vault_secret_options_string
  ansible.builtin.set_fact:
    _vault_secret_options_string: ''
  run_once: yes

- name: Ensure _vault_secret_options_string
  ansible.builtin.set_fact:
    _vault_secret_options_string: "{{ _vault_secret_options_string | default('') }} -{{ item.key }}={{ item.value }}"
  loop: "{{ query('dict', _vault_secret_engine_options) }}"
  loop_control:
    label: "{{ item.key }}"
  run_once: yes

# - name: Print _vault_secret_options_string
#   ansible.builtin.debug:
#     msg: "_vault_secret_options_string: {{ _vault_secret_options_string }}"
#   run_once: yes

- name: Ensure vault enable secret engine
  ansible.builtin.shell:
    cmd: >
      docker exec -e VAULT_TOKEN='{{ _vault_root_token }}' vault 
      vault secrets enable {{ _vault_secret_options_string | default('') }} {{ _vault_secret_engine.engine }}
      | tee {{ vault_home }}/ansible_done_vault_secret_enable_{{ _vault_secret_engine.engine }}
    creates: "{{ vault_home }}/ansible_done_vault_secret_enable_{{ _vault_secret_engine.engine }}"
  run_once: yes

...