---

- name: Get vault status output
  ansible.builtin.shell:
    cmd: >
      {{ _vault_command_prefix }} {{ _vault_command_postfix }} status -format=json || /bin/true
  register: _vault_status_output
  changed_when: false
  ignore_errors: true

- name: Set fact _vault_status
  ansible.builtin.set_fact:
    _vault_status: "{{ _vault_status_output.stdout }}"

- name: Print _vault_status
  ansible.builtin.debug:
    msg: "_vault_status: {{ _vault_status }}"

...
