---

- name: Ensure vault service is running (and enabled)
  ansible.builtin.systemd:
    name:    vault
    state:   started
    enabled: true
  retries:  "{{ vault_service_wait_retries }}"
  delay:    "{{ vault_service_wait_delay }}"

- name: Wait vault service active
  ansible.builtin.systemd:
    name: vault
  register: _vault_service_status
  until:    _vault_service_status.status.ActiveState == "active"
  retries:  "{{ vault_service_wait_retries }}"
  delay:    "{{ vault_service_wait_delay }}"

...
