---

- name: Ensure _vault_root_token

  block:
    - name: Ensure vault operator generate-root -init
      ansible.builtin.command:
        cmd: >
          docker exec vault
          vault operator generate-root -format=json -init
      register: _vault_operator_generate_root_init_result

    - name: Set fact _vault_operator_generate_root_init
      ansible.builtin.set_fact:
        _vault_operator_generate_root_init: "{{ _vault_operator_generate_root_init_result.stdout }}"

    - name: Ensure vault operator generate-root
      ansible.builtin.shell:
        cmd: >
          echo {{ _vault_unseal_keys[_vault_unseal_key_index] }} |
          docker exec --interactive vault
          vault operator generate-root -format=json -nonce={{ _vault_operator_generate_root_init.nonce }} -
      loop: "{{ range(0, vault_key_threshold) | list }}"
      loop_control:
        index_var: _vault_unseal_key_index
      register: _vault_operator_generate_root_results

    - name: Set fact _vault_operator_generate_root
      ansible.builtin.set_fact:
        _vault_operator_generate_root: "{{ _vault_operator_generate_root_results.results[vault_key_threshold-1].stdout }}"

    - name: Ensure vault operator generate-root decode
      ansible.builtin.shell:
        cmd: >
          docker exec vault
          vault operator generate-root -format=json -decode={{ _vault_operator_generate_root.encoded_root_token }} -otp={{ _vault_operator_generate_root_init.otp }}
      register: _vault_operator_generate_root_decode_result

    - name: Set fact _vault_operator_generate_root_decode
      ansible.builtin.set_fact:
        _vault_operator_generate_root_decode: "{{ _vault_operator_generate_root_decode_result.stdout }}"

    - name: Set fact _vault_root_token
      ansible.builtin.set_fact:
        _vault_root_token: "{{ _vault_operator_generate_root_decode.token }}"

  run_once: true
  when: vault_revoke_root_token and _vault_initialized

- name: Ensure vault create root token
  ansible.builtin.shell:
    cmd: >
      docker exec -e VAULT_TOKEN='{{ _vault_root_token }}' vault 
      vault token create -ttl {{ vault_root_token_ttl }} -format=json
  register: _vault_create_root_token_result
  run_once: yes

- name: Set fact _vault_create_root_token
  ansible.builtin.set_fact:
    _vault_create_root_token: "{{ _vault_create_root_token_result.stdout }}"
  run_once: yes

- name: Set fact vault_root_token
  ansible.builtin.set_fact:
    vault_root_token: "{{ _vault_create_root_token.auth.client_token }}"
  run_once: yes

- name: Ensure vault revoke root token
  ansible.builtin.shell:
    cmd: >
      docker exec -e VAULT_TOKEN='{{ _vault_root_token }}' vault 
      vault token revoke -mode=orphan {{ _vault_root_token }}
  register: _vault_revoke_root_token_result
  when: vault_revoke_root_token
  run_once: yes

- name: Ensure _vault_root_token
  ansible.builtin.set_fact:
    _vault_root_token: "{{  vault_root_token }}"
  when: vault_revoke_root_token
  run_once: yes

...