---

- name: Ensure _vault_write_kv
  ansible.builtin.set_fact:
    _vault_write_kv: "{{ _vault_write.kv | default({}) | default(omit) }}"
  run_once: yes

- name: Ensure initialize _vault_write_kv_string
  ansible.builtin.set_fact:
    _vault_write_kv_string: ''
  run_once: yes

- name: Ensure _vault_write_kv_string
  ansible.builtin.set_fact:
    _vault_write_kv_string: "{{ _vault_write_kv_string | default('') }} {{ item.key }}={{ item.value }}"
  loop: "{{ query('dict', _vault_write_kv) }}"
  loop_control:
    label: "{{ item.key }}"
  run_once: yes

# - name: Print _vault_write_kv_string
#   ansible.builtin.debug:
#     msg: "_vault_write_kv_string: {{ _vault_write_kv_string }}"
#   run_once: yes

- name: Ensure vault write
  ansible.builtin.shell:
    cmd: >
      docker exec -e VAULT_TOKEN='{{ _vault_root_token }}' vault 
      vault write {{ _vault_write.path }} {{ _vault_write_kv_string }}
      | tee {{ vault_home }}/ansible_done_vault_write_{{ _vault_write.path | regex_replace('/', '_slash_') }}
    creates: "{{ vault_home }}/ansible_done_vault_write_{{ _vault_write.path | regex_replace('/', '_slash_') }}"
  run_once: yes

...